title: Nawal Kishor Hazarika
logo: /assets/images/nkh 124 kb.jpg

description: Hi! I am Nawal. I have completed my Integrated M.Sc. in Mathematics from Tezpur University this year. Recently I have been studying Commutative Algebra and the basics of Algebraic Geometry.
#show_downloads: true
theme: jekyll-theme-minimal
